apiVersion: v1
kind: Secret
metadata:
  name: my-spring-app-db-secret
type: Opaque
data:
  # Логин и пароль нужно закодировать в base64
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.auth.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
