replicaCount: 1

image:
  repository: iskaltygin/my-spring-app
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: arch.homework
  path: /
  annotations: {}
  tls: []

postgresql:
  auth:
    username: testuser
    password: testpass
    database: testdb
  primary:
    persistence:
      enabled: false  # Отключить постоянное хранилище для упрощения разработки



resources: {}
